import type { Metadata } from 'next';
import './globals.css';
import Header from './_component/Header';
import Footer from './_component/Footer';

export const metadata: Metadata = {
    title: 'Damgon Research',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode,
}) {
    return (
        <html lang='ko'>
            <body>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
